// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleWKT

/// use case 1
/// A log entry when modification(creation, update, deletion) is made to a
/// BackupPlan
public struct BackupPlanChange: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The full name of the old BackupPlan resource that is being modified.
  /// Empty for creation.
  /// Format: projects/{project}/locations/{location}/backupPlans/{backup_plan}
  public var backupPlan: Swift.String = Swift.String()

  /// Type of the change is being made.
  public var changeType: ChangeType = ChangeType()

  /// Modification details.
  public var updateMask: GoogleWKT.FieldMask? = nil

  /// The input BackupPlan resource with the updated fields populated to update
  /// the source BackupPlan to.
  public var inputBackupPlan: LoggedBackupPlan? = nil

  /// The error code and message.
  public var error: GoogleRpc.Status? = nil

  /// The metadata of the BackupPlan.
  public var backupPlanMetadata: LoggedBackupPlanMetadata? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupPlanChange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupPlanChange().with { $0.backupPlan = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let backupPlan = CodingKeys(stringValue: "backupPlan")
    static let changeType = CodingKeys(stringValue: "changeType")
    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let inputBackupPlan = CodingKeys(stringValue: "inputBackupPlan")
    static let error = CodingKeys(stringValue: "error")
    static let backupPlanMetadata = CodingKeys(stringValue: "backupPlanMetadata")

    static let _knownKeys: Set<Swift.String> = [
      "backupPlan",
      "changeType",
      "updateMask",
      "inputBackupPlan",
      "error",
      "backupPlanMetadata",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupPlan) {
      self.backupPlan = value
    }
    if let value = try container.decodeIfPresent(ChangeType.self, forKey: .changeType) {
      self.changeType = value
    }
    self.updateMask = try container.decodeIfPresent(GoogleWKT.FieldMask.self, forKey: .updateMask)
    self.inputBackupPlan = try container.decodeIfPresent(
      LoggedBackupPlan.self, forKey: .inputBackupPlan)
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    self.backupPlanMetadata = try container.decodeIfPresent(
      LoggedBackupPlanMetadata.self, forKey: .backupPlanMetadata)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.backupPlan, forKey: .backupPlan)
    try container.encode(self.changeType, forKey: .changeType)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encodeIfPresent(self.inputBackupPlan, forKey: .inputBackupPlan)
    try container.encodeIfPresent(self.error, forKey: .error)
    try container.encodeIfPresent(self.backupPlanMetadata, forKey: .backupPlanMetadata)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.logging.v1.BackupPlanChange"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
