// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// use case 2
/// A log entry when modification(creation, update, deletion) is made to a
/// Backup
public struct BackupChange: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The full name of the Backup resource that is being modified.
  /// Format:
  /// projects/{project}/locations/{location}/backupPlans/{backup_plan}/backups/{backup}
  public var backup: Swift.String = Swift.String()

  /// Type of the change is being made.
  public var changeType: ChangeType = ChangeType()

  /// Whether the change is made manually or automatically.
  public var scheduled: Swift.Bool = Swift.Bool()

  /// Modification details.
  public var updateMask: GoogleWKT.WKTFieldMask? = nil

  /// The input Backup resource with the updated fields populated to update
  /// the source Backup to, or the backup created automatically from retention
  /// policy.
  public var inputBackup: LoggedBackup? = nil

  /// The error code and message.
  public var error: GoogleRpc.Status? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackupChange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupChange().with { $0.backup = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let backup = CodingKeys(stringValue: "backup")
    static let changeType = CodingKeys(stringValue: "changeType")
    static let scheduled = CodingKeys(stringValue: "scheduled")
    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let inputBackup = CodingKeys(stringValue: "inputBackup")
    static let error = CodingKeys(stringValue: "error")

    static let _knownKeys: Set<Swift.String> = [
      "backup",
      "changeType",
      "scheduled",
      "updateMask",
      "inputBackup",
      "error",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backup) {
      self.backup = value
    }
    if let value = try container.decodeIfPresent(ChangeType.self, forKey: .changeType) {
      self.changeType = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .scheduled) {
      self.scheduled = value
    }
    self.updateMask = try container.decodeIfPresent(
      GoogleWKT.WKTFieldMask.self, forKey: .updateMask)
    self.inputBackup = try container.decodeIfPresent(LoggedBackup.self, forKey: .inputBackup)
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.backup, forKey: .backup)
    try container.encode(self.changeType, forKey: .changeType)
    try container.encode(self.scheduled, forKey: .scheduled)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encodeIfPresent(self.inputBackup, forKey: .inputBackup)
    try container.encodeIfPresent(self.error, forKey: .error)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.logging.v1.BackupChange"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
