// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// use case 5
/// A log entry when modification(creation, update, deletion) is made to a
/// backupChannel.
public struct BackupChannelChange: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The full name of the BackupChannel resource that is being modified.
  /// Empty for creation.
  /// Format:
  /// projects/{project}/locations/{location}/backupChannels/{backup_channel}
  public var backupChannel: Swift.String = Swift.String()

  /// The type of change is being made.
  public var changeType: ChangeType = ChangeType()

  /// Modification details.
  public var updateMask: GoogleCloudWKT.FieldMask? = nil

  /// The input BackupChannel resource with the updated fields populated to
  /// update the source BackupChannel to.
  public var inputBackupChannel: LoggedBackupChannel? = nil

  /// The error code and message.
  public var error: GoogleRpc.Status? = nil

  /// Initialize a new instance of `BackupChannelChange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupChannelChange().with { $0.backupChannel = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.logging.v1.BackupChannelChange"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
