// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// use case 2
/// A log entry when modification(creation, update, deletion) is made to a
/// Backup
public struct BackupChange: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The full name of the Backup resource that is being modified.
  /// Format:
  /// projects/{project}/locations/{location}/backupPlans/{backup_plan}/backups/{backup}
  public var backup: Swift.String = Swift.String()

  /// Type of the change is being made.
  public var changeType: ChangeType = ChangeType()

  /// Whether the change is made manually or automatically.
  public var scheduled: Swift.Bool = Swift.Bool()

  /// Modification details.
  public var updateMask: GoogleCloudWKT.FieldMask? = nil

  /// The input Backup resource with the updated fields populated to update
  /// the source Backup to, or the backup created automatically from retention
  /// policy.
  public var inputBackup: LoggedBackup? = nil

  /// The error code and message.
  public var error: GoogleRpc.Status? = nil

  /// Initialize a new instance of `BackupChange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackupChange().with { $0.backup = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.logging.v1.BackupChange"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
