// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// BackupPlan as stored in Platform log. It's used to log the details of
/// a createBackupPlan/updateBackupPlan request, so only fields that can be taken
/// from user input are included here.
public struct LoggedBackupPlan: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// User specified descriptive string for this BackupPlan.
  public var description: Swift.String = Swift.String()

  /// GCP resource name of the source cluster for this BackupPlan.
  public var cluster: Swift.String = Swift.String()

  /// RetentionPolicy governs lifecycle of Backups created under this plan.
  public var retentionPolicy: LoggedBackupPlan.RetentionPolicy? = nil

  /// A set of custom labels supplied by user.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Defines scheduled Backup creation under this BackupPlan.
  public var backupSchedule: LoggedBackupPlan.Schedule? = nil

  /// A flag indicates whether the plan has been deactivated.
  public var deactivated: Swift.Bool = Swift.Bool()

  /// Defines backup configuration of this BackupPlan.
  public var backupConfig: LoggedBackupPlan.BackupConfig? = nil

  /// A number that represents the current risk level of this BackupPlan from RPO
  /// perspective with 1 being no risk and 5 being highest risk.
  /// Deprecated: Use LoggedBackupPlanMetadata.rpo_risk_level instead.
  @available(*, deprecated)
  public var rpoRiskLevel: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `LoggedBackupPlan`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LoggedBackupPlan().with { $0.description = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let description = CodingKeys(stringValue: "description")
    static let cluster = CodingKeys(stringValue: "cluster")
    static let retentionPolicy = CodingKeys(stringValue: "retentionPolicy")
    static let labels = CodingKeys(stringValue: "labels")
    static let backupSchedule = CodingKeys(stringValue: "backupSchedule")
    static let deactivated = CodingKeys(stringValue: "deactivated")
    static let backupConfig = CodingKeys(stringValue: "backupConfig")
    static let rpoRiskLevel = CodingKeys(stringValue: "rpoRiskLevel")

    static let _knownKeys: Set<Swift.String> = [
      "description",
      "cluster",
      "retentionPolicy",
      "labels",
      "backupSchedule",
      "deactivated",
      "backupConfig",
      "rpoRiskLevel",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cluster) {
      self.cluster = value
    }
    self.retentionPolicy = try container.decodeIfPresent(
      LoggedBackupPlan.RetentionPolicy.self, forKey: .retentionPolicy)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.backupSchedule = try container.decodeIfPresent(
      LoggedBackupPlan.Schedule.self, forKey: .backupSchedule)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .deactivated) {
      self.deactivated = value
    }
    self.backupConfig = try container.decodeIfPresent(
      LoggedBackupPlan.BackupConfig.self, forKey: .backupConfig)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .rpoRiskLevel) {
      self.rpoRiskLevel = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.cluster, forKey: .cluster)
    try container.encodeIfPresent(self.retentionPolicy, forKey: .retentionPolicy)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.backupSchedule, forKey: .backupSchedule)
    try container.encode(self.deactivated, forKey: .deactivated)
    try container.encodeIfPresent(self.backupConfig, forKey: .backupConfig)
    try container.encode(self.rpoRiskLevel, forKey: .rpoRiskLevel)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// RentionPolicy is an inner message type to define:
  /// 1. When to automatically delete Backups created under this BackupPlan
  /// 2. A plan level minimum Backup retain days which blocks deletion
  /// 3. Lock to disallow any policy updates
  public struct RetentionPolicy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Number of days during which deletion of a Backup created under this
    /// BackupPlan will be blocked.
    public var backupDeleteLockDays: Swift.Int32 = Swift.Int32()

    /// Number of days after which the service will delete a Backup.
    /// If specified, a Backup created under this BackupPlan will be
    /// automatically deleted after its age reaches create_time +
    /// backup_retain_days.
    public var backupRetainDays: Swift.Int32 = Swift.Int32()

    /// A flag denotes that the retention policy of this BackupPlan is locked.
    /// If set to True, no further update is allowed on this policy, including
    /// the 'locked' field itself.
    /// Default to False.
    public var locked: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `RetentionPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RetentionPolicy().with { $0.backupDeleteLockDays = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let backupDeleteLockDays = CodingKeys(stringValue: "backupDeleteLockDays")
      static let backupRetainDays = CodingKeys(stringValue: "backupRetainDays")
      static let locked = CodingKeys(stringValue: "locked")

      static let _knownKeys: Set<Swift.String> = [
        "backupDeleteLockDays",
        "backupRetainDays",
        "locked",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .backupDeleteLockDays)
      {
        self.backupDeleteLockDays = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .backupRetainDays) {
        self.backupRetainDays = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .locked) {
        self.locked = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.backupDeleteLockDays, forKey: .backupDeleteLockDays)
      try container.encode(self.backupRetainDays, forKey: .backupRetainDays)
      try container.encode(self.locked, forKey: .locked)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.gkebackup.logging.v1.LoggedBackupPlan.RetentionPolicy"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Schedule, an inner message type defines a cron schedule.
  public struct Schedule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// A cron style string schedule on which an operation will be executed.
    public var cronSchedule: Swift.String = Swift.String()

    /// A flag to toggle scheduled operation.
    public var paused: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `Schedule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Schedule().with { $0.cronSchedule = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let cronSchedule = CodingKeys(stringValue: "cronSchedule")
      static let paused = CodingKeys(stringValue: "paused")

      static let _knownKeys: Set<Swift.String> = [
        "cronSchedule",
        "paused",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cronSchedule) {
        self.cronSchedule = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .paused) {
        self.paused = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.cronSchedule, forKey: .cronSchedule)
      try container.encode(self.paused, forKey: .paused)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.logging.v1.LoggedBackupPlan.Schedule"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// BackupConfig, an inner message type defines the configuration of creating
  /// a backup from this BackupPlan
  public struct BackupConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// A boolean flag specifies whether volume data should be backed up
    public var includeVolumeData: Swift.Bool = Swift.Bool()

    /// A boolean flag specifies whether secrets should be backed up
    public var includeSecrets: Swift.Bool = Swift.Bool()

    /// Custom encryption key. For preview, support GCP KMS only.
    /// This only contains the key metadata, and no key material.
    public var encryptionKey: EncryptionKey? = nil

    public var backupScope: OneOf_BackupScope? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `BackupConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BackupConfig().with { $0.allNamespaces = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let allNamespaces = CodingKeys(stringValue: "allNamespaces")
      static let selectedNamespaces = CodingKeys(stringValue: "selectedNamespaces")
      static let selectedApplications = CodingKeys(stringValue: "selectedApplications")
      static let includeVolumeData = CodingKeys(stringValue: "includeVolumeData")
      static let includeSecrets = CodingKeys(stringValue: "includeSecrets")
      static let encryptionKey = CodingKeys(stringValue: "encryptionKey")

      static let _knownKeys: Set<Swift.String> = [
        "allNamespaces",
        "selectedNamespaces",
        "selectedApplications",
        "includeVolumeData",
        "includeSecrets",
        "encryptionKey",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .includeVolumeData) {
        self.includeVolumeData = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .includeSecrets) {
        self.includeSecrets = value
      }
      self.encryptionKey = try container.decodeIfPresent(EncryptionKey.self, forKey: .encryptionKey)

      var backupScope: OneOf_BackupScope? = nil
      let backupScopeCheckAndSet = {
        if backupScope != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'backupScope'"))
        }
        backupScope = $0
      }
      if let allNamespaces = try container.decodeIfPresent(Swift.Bool.self, forKey: .allNamespaces)
      {
        try backupScopeCheckAndSet(.allNamespaces(allNamespaces))
      }
      if let selectedNamespaces = try container.decodeIfPresent(
        Namespaces?.self, forKey: .selectedNamespaces)
      {
        try backupScopeCheckAndSet(.selectedNamespaces(selectedNamespaces))
      }
      if let selectedApplications = try container.decodeIfPresent(
        NamespacedNames?.self, forKey: .selectedApplications)
      {
        try backupScopeCheckAndSet(.selectedApplications(selectedApplications))
      }
      self.backupScope = backupScope
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.includeVolumeData, forKey: .includeVolumeData)
      try container.encode(self.includeSecrets, forKey: .includeSecrets)
      try container.encodeIfPresent(self.encryptionKey, forKey: .encryptionKey)

      if let choice = self.backupScope {
        switch choice {
        case .allNamespaces(let value):
          try container.encode(value, forKey: .allNamespaces)
        case .selectedNamespaces(let value):
          try container.encode(value, forKey: .selectedNamespaces)
        case .selectedApplications(let value):
          try container.encode(value, forKey: .selectedApplications)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public enum OneOf_BackupScope: Codable, Equatable, Sendable {
      /// If set to true, backup whole cluster
      case allNamespaces(Swift.Bool)
      /// If set, backup the list of namespaces
      indirect case selectedNamespaces(Namespaces?)
      /// If set, backup the list of applications
      indirect case selectedApplications(NamespacedNames?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.logging.v1.LoggedBackupPlan.BackupConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.logging.v1.LoggedBackupPlan"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
