// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// RestorePlan as stored in Platform log. It's used to log the details of
/// a createRestorePlan/updateRestorePlan request, so only fields that can be
/// taken from user input are included here.
public struct LoggedRestorePlan: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// User specified descriptive string for this RestorePlan.
  public var description: Swift.String = Swift.String()

  /// The BackupPlan from which Backups may be used as the source
  /// for Restores created via this RestorePlan.
  /// Format: projects/*/locations/*/backupPlans/*.
  public var backupPlan: Swift.String = Swift.String()

  /// The target cluster into which Restores created via this RestorePlan
  /// will restore data. NOTE: the cluster's region must be the same as the
  /// RestorePlan.
  /// Possible formats:
  ///   1. projects/*/locations/*/clusters/*
  ///   2. projects/*/zones/*/clusters/*
  public var cluster: Swift.String = Swift.String()

  /// Configuration of Restores created via this RestorePlan.
  public var restoreConfig: RestoreConfig? = nil

  /// A set of custom labels supplied by user.
  public var labels: [Swift.String: Swift.String] = [:]

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LoggedRestorePlan`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LoggedRestorePlan().with { $0.description = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let description = CodingKeys(stringValue: "description")
    static let backupPlan = CodingKeys(stringValue: "backupPlan")
    static let cluster = CodingKeys(stringValue: "cluster")
    static let restoreConfig = CodingKeys(stringValue: "restoreConfig")
    static let labels = CodingKeys(stringValue: "labels")

    static let _knownKeys: Set<Swift.String> = [
      "description",
      "backupPlan",
      "cluster",
      "restoreConfig",
      "labels",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupPlan) {
      self.backupPlan = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cluster) {
      self.cluster = value
    }
    self.restoreConfig = try container.decodeIfPresent(RestoreConfig.self, forKey: .restoreConfig)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.description, forKey: .description)
    try container.encode(self.backupPlan, forKey: .backupPlan)
    try container.encode(self.cluster, forKey: .cluster)
    try container.encodeIfPresent(self.restoreConfig, forKey: .restoreConfig)
    try container.encode(self.labels, forKey: .labels)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.logging.v1.LoggedRestorePlan"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
