// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Backup as stored in Platform log. It's used to log the details of
/// a createBackup/updateBackup request, so only fields that can be taken
/// from API calls are included here.
public struct LoggedBackup: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// A set of custom labels supplied by user.
  public var labels: [Swift.String: Swift.String] = [:]

  /// delete_lock_days specifies the number of days from the create_time of this
  /// Backup before which deletion will be blocked.
  public var deleteLockDays: Swift.Int32 = Swift.Int32()

  /// retain_days specifies the desired number of days from the create_time of
  /// this Backup after which it will be automatically deleted.
  public var retainDays: Swift.Int32 = Swift.Int32()

  /// User specified descriptive string for this Backup.
  public var description: Swift.String = Swift.String()

  /// Current state of the Backup
  public var state: LoggedBackup.State = LoggedBackup.State()

  /// Human-readable description of why the backup is in the current `state`.
  public var stateReason: Swift.String = Swift.String()

  /// Initialize a new instance of `LoggedBackup`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LoggedBackup().with { $0.labels = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// State
  public enum State: Codable, Equatable, Sendable {
    /// The Backup resource is in the process of being created.
    case unspecified
    /// The Backup resource has been created and the associated BackupJob
    /// Kubernetes resource has been injected into the source cluster.
    case creating
    /// The gkebackup agent in the cluster has begun executing the backup
    /// operation.
    case inProgress
    /// The backup operation has completed successfully.
    case succeeded
    /// The backup operation has failed.
    case failed
    /// This Backup resource (and its associated artifacts) is in the process
    /// of being deleted.
    case deleting
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .inProgress: return 2
      case .succeeded: return 3
      case .failed: return 4
      case .deleting: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .inProgress: return "IN_PROGRESS"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .deleting: return "DELETING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "IN_PROGRESS": self = .inProgress
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "DELETING": self = .deleting
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .inProgress
      case 3: self = .succeeded
      case 4: self = .failed
      case 5: self = .deleting
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .inProgress: return try container.encode(2)
      case .succeeded: return try container.encode(3)
      case .failed: return try container.encode(4)
      case .deleting: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.logging.v1.LoggedBackup"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
