// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// LoggedBackupPlanMetadata as stored in Platform log. It's used to log the
/// details of a BackupPlan, which are not provided by users, but are filled
/// by the service.
public struct LoggedBackupPlanMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The name of the backup channel if any.
  public var backupChannel: Swift.String = Swift.String()

  /// A number that represents the current risk level of this BackupPlan from RPO
  /// perspective with 1 being no risk and 5 being highest risk.
  public var rpoRiskLevel: Swift.Int32 = Swift.Int32()

  /// The reason for the current risk level of this BackupPlan from RPO
  /// perspective.
  public var rpoRiskReason: Swift.String = Swift.String()

  /// Initialize a new instance of `LoggedBackupPlanMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LoggedBackupPlanMetadata().with { $0.backupChannel = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.logging.v1.LoggedBackupPlanMetadata"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
