// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// BackupPlan as stored in Platform log. It's used to log the details of
/// a createBackupPlan/updateBackupPlan request, so only fields that can be taken
/// from user input are included here.
public struct LoggedBackupPlan: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// User specified descriptive string for this BackupPlan.
  public var description: Swift.String = Swift.String()

  /// GCP resource name of the source cluster for this BackupPlan.
  public var cluster: Swift.String = Swift.String()

  /// RetentionPolicy governs lifecycle of Backups created under this plan.
  public var retentionPolicy: LoggedBackupPlan.RetentionPolicy? = nil

  /// A set of custom labels supplied by user.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Defines scheduled Backup creation under this BackupPlan.
  public var backupSchedule: LoggedBackupPlan.Schedule? = nil

  /// A flag indicates whether the plan has been deactivated.
  public var deactivated: Swift.Bool = Swift.Bool()

  /// Defines backup configuration of this BackupPlan.
  public var backupConfig: LoggedBackupPlan.BackupConfig? = nil

  /// A number that represents the current risk level of this BackupPlan from RPO
  /// perspective with 1 being no risk and 5 being highest risk.
  /// Deprecated: Use LoggedBackupPlanMetadata.rpo_risk_level instead.
  @available(*, deprecated)
  public var rpoRiskLevel: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `LoggedBackupPlan`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LoggedBackupPlan().with { $0.description = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// RentionPolicy is an inner message type to define:
  /// 1. When to automatically delete Backups created under this BackupPlan
  /// 2. A plan level minimum Backup retain days which blocks deletion
  /// 3. Lock to disallow any policy updates
  public struct RetentionPolicy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Number of days during which deletion of a Backup created under this
    /// BackupPlan will be blocked.
    public var backupDeleteLockDays: Swift.Int32 = Swift.Int32()

    /// Number of days after which the service will delete a Backup.
    /// If specified, a Backup created under this BackupPlan will be
    /// automatically deleted after its age reaches create_time +
    /// backup_retain_days.
    public var backupRetainDays: Swift.Int32 = Swift.Int32()

    /// A flag denotes that the retention policy of this BackupPlan is locked.
    /// If set to True, no further update is allowed on this policy, including
    /// the 'locked' field itself.
    /// Default to False.
    public var locked: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `RetentionPolicy`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RetentionPolicy().with { $0.backupDeleteLockDays = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.gkebackup.logging.v1.LoggedBackupPlan.RetentionPolicy"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Schedule, an inner message type defines a cron schedule.
  public struct Schedule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// A cron style string schedule on which an operation will be executed.
    public var cronSchedule: Swift.String = Swift.String()

    /// A flag to toggle scheduled operation.
    public var paused: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `Schedule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Schedule().with { $0.cronSchedule = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.logging.v1.LoggedBackupPlan.Schedule"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// BackupConfig, an inner message type defines the configuration of creating
  /// a backup from this BackupPlan
  public struct BackupConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// A boolean flag specifies whether volume data should be backed up
    public var includeVolumeData: Swift.Bool = Swift.Bool()

    /// A boolean flag specifies whether secrets should be backed up
    public var includeSecrets: Swift.Bool = Swift.Bool()

    /// Custom encryption key. For preview, support GCP KMS only.
    /// This only contains the key metadata, and no key material.
    public var encryptionKey: EncryptionKey? = nil

    public var backupScope: OneOf_BackupScope? = nil

    /// Initialize a new instance of `BackupConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BackupConfig().with { $0.allNamespaces = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case allNamespaces = "allNamespaces"
      case selectedNamespaces = "selectedNamespaces"
      case selectedApplications = "selectedApplications"
      case includeVolumeData = "includeVolumeData"
      case includeSecrets = "includeSecrets"
      case encryptionKey = "encryptionKey"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.includeVolumeData = try container.decode(Swift.Bool.self, forKey: .includeVolumeData)
      self.includeSecrets = try container.decode(Swift.Bool.self, forKey: .includeSecrets)
      self.encryptionKey = try container.decodeIfPresent(EncryptionKey.self, forKey: .encryptionKey)

      var backupScope: OneOf_BackupScope? = nil
      let backupScopeCheckAndSet = {
        if backupScope != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'backupScope'"))
        }
        backupScope = $0
      }
      if let allNamespaces = try container.decodeIfPresent(Swift.Bool.self, forKey: .allNamespaces)
      {
        try backupScopeCheckAndSet(.allNamespaces(allNamespaces))
      }
      if let selectedNamespaces = try container.decodeIfPresent(
        Namespaces?.self, forKey: .selectedNamespaces)
      {
        try backupScopeCheckAndSet(.selectedNamespaces(selectedNamespaces))
      }
      if let selectedApplications = try container.decodeIfPresent(
        NamespacedNames?.self, forKey: .selectedApplications)
      {
        try backupScopeCheckAndSet(.selectedApplications(selectedApplications))
      }
      self.backupScope = backupScope
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.includeVolumeData, forKey: .includeVolumeData)
      try container.encode(self.includeSecrets, forKey: .includeSecrets)
      try container.encode(self.encryptionKey, forKey: .encryptionKey)

      if let choice = self.backupScope {
        switch choice {
        case .allNamespaces(let value):
          try container.encode(value, forKey: .allNamespaces)
        case .selectedNamespaces(let value):
          try container.encode(value, forKey: .selectedNamespaces)
        case .selectedApplications(let value):
          try container.encode(value, forKey: .selectedApplications)
        }
      }
    }

    public enum OneOf_BackupScope: Codable, Equatable, Sendable {
      /// If set to true, backup whole cluster
      case allNamespaces(Swift.Bool)
      /// If set, backup the list of namespaces
      indirect case selectedNamespaces(Namespaces?)
      /// If set, backup the list of applications
      indirect case selectedApplications(NamespacedNames?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.gkebackup.logging.v1.LoggedBackupPlan.BackupConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.logging.v1.LoggedBackupPlan"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
