// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// LoggedBackupPlanMetadata as stored in Platform log. It's used to log the
/// details of a BackupPlan, which are not provided by users, but are filled
/// by the service.
public struct LoggedBackupPlanMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The name of the backup channel if any.
  public var backupChannel: Swift.String = Swift.String()

  /// A number that represents the current risk level of this BackupPlan from RPO
  /// perspective with 1 being no risk and 5 being highest risk.
  public var rpoRiskLevel: Swift.Int32 = Swift.Int32()

  /// The reason for the current risk level of this BackupPlan from RPO
  /// perspective.
  public var rpoRiskReason: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `LoggedBackupPlanMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LoggedBackupPlanMetadata().with { $0.backupChannel = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let backupChannel = CodingKeys(stringValue: "backupChannel")
    static let rpoRiskLevel = CodingKeys(stringValue: "rpoRiskLevel")
    static let rpoRiskReason = CodingKeys(stringValue: "rpoRiskReason")

    static let _knownKeys: Set<Swift.String> = [
      "backupChannel",
      "rpoRiskLevel",
      "rpoRiskReason",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .backupChannel) {
      self.backupChannel = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .rpoRiskLevel) {
      self.rpoRiskLevel = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .rpoRiskReason) {
      self.rpoRiskReason = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.backupChannel, forKey: .backupChannel)
    try container.encode(self.rpoRiskLevel, forKey: .rpoRiskLevel)
    try container.encode(self.rpoRiskReason, forKey: .rpoRiskReason)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.logging.v1.LoggedBackupPlanMetadata"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
