// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleWKT

/// use case 6
/// A log entry when modification(creation, update, deletion) is made to a
/// restoreChannel.
public struct RestoreChannelChange: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The full name of the RestoreChannel resource that is being modified.
  /// Empty for creation.
  /// Format:
  /// projects/{project}/locations/{location}/restoreChannels/{restore_channel}
  public var restoreChannel: Swift.String = Swift.String()

  /// The type of change is being made.
  public var changeType: ChangeType = ChangeType()

  /// Modification details.
  public var updateMask: GoogleWKT.FieldMask? = nil

  /// The input RestoreChannel resource with the updated fields populated to
  /// update the source RestoreChannel to.
  public var inputRestoreChannel: LoggedRestoreChannel? = nil

  /// The error code and message.
  public var error: GoogleRpc.Status? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `RestoreChannelChange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RestoreChannelChange().with { $0.restoreChannel = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let restoreChannel = CodingKeys(stringValue: "restoreChannel")
    static let changeType = CodingKeys(stringValue: "changeType")
    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let inputRestoreChannel = CodingKeys(stringValue: "inputRestoreChannel")
    static let error = CodingKeys(stringValue: "error")

    static let _knownKeys: Set<Swift.String> = [
      "restoreChannel",
      "changeType",
      "updateMask",
      "inputRestoreChannel",
      "error",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .restoreChannel) {
      self.restoreChannel = value
    }
    if let value = try container.decodeIfPresent(ChangeType.self, forKey: .changeType) {
      self.changeType = value
    }
    self.updateMask = try container.decodeIfPresent(GoogleWKT.FieldMask.self, forKey: .updateMask)
    self.inputRestoreChannel = try container.decodeIfPresent(
      LoggedRestoreChannel.self, forKey: .inputRestoreChannel)
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.restoreChannel, forKey: .restoreChannel)
    try container.encode(self.changeType, forKey: .changeType)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encodeIfPresent(self.inputRestoreChannel, forKey: .inputRestoreChannel)
    try container.encodeIfPresent(self.error, forKey: .error)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.logging.v1.RestoreChannelChange"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
