// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// use case 3
/// A log entry when modification(creation, update, deletion) is made to a
/// restorePlan.
public struct RestorePlanChange: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The full name of the RestorePlan resource that is being modified.
  /// Empty for creation.
  /// Format: projects/*/locations/*/restorePlans/*
  public var restorePlan: Swift.String = Swift.String()

  /// Type of the change is being made.
  public var changeType: ChangeType = ChangeType()

  /// Modification details.
  public var updateMask: GoogleCloudWKT.FieldMask? = nil

  /// The input RestorePlan resource with the updated fields populated to update
  /// the source RestorePlan to.
  public var inputRestorePlan: LoggedRestorePlan? = nil

  /// The error code and message.
  public var error: GoogleRpc.Status? = nil

  /// The metadata of the RestorePlan.
  public var restorePlanMetadata: LoggedRestorePlanMetadata? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `RestorePlanChange`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RestorePlanChange().with { $0.restorePlan = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let restorePlan = CodingKeys(stringValue: "restorePlan")
    static let changeType = CodingKeys(stringValue: "changeType")
    static let updateMask = CodingKeys(stringValue: "updateMask")
    static let inputRestorePlan = CodingKeys(stringValue: "inputRestorePlan")
    static let error = CodingKeys(stringValue: "error")
    static let restorePlanMetadata = CodingKeys(stringValue: "restorePlanMetadata")

    static let _knownKeys: Set<Swift.String> = [
      "restorePlan",
      "changeType",
      "updateMask",
      "inputRestorePlan",
      "error",
      "restorePlanMetadata",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .restorePlan) {
      self.restorePlan = value
    }
    if let value = try container.decodeIfPresent(ChangeType.self, forKey: .changeType) {
      self.changeType = value
    }
    self.updateMask = try container.decodeIfPresent(
      GoogleCloudWKT.FieldMask.self, forKey: .updateMask)
    self.inputRestorePlan = try container.decodeIfPresent(
      LoggedRestorePlan.self, forKey: .inputRestorePlan)
    self.error = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .error)
    self.restorePlanMetadata = try container.decodeIfPresent(
      LoggedRestorePlanMetadata.self, forKey: .restorePlanMetadata)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.restorePlan, forKey: .restorePlan)
    try container.encode(self.changeType, forKey: .changeType)
    try container.encodeIfPresent(self.updateMask, forKey: .updateMask)
    try container.encodeIfPresent(self.inputRestorePlan, forKey: .inputRestorePlan)
    try container.encodeIfPresent(self.error, forKey: .error)
    try container.encodeIfPresent(self.restorePlanMetadata, forKey: .restorePlanMetadata)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.gkebackup.logging.v1.RestorePlanChange"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
